- name: Upload file to remote host
  hosts: all
  become: true
  become_method: sudo

  tasks:
    - name: Upload the nginx config file
      copy:
        src: ./nginx.conf
        dest: /home/robinmollah/nginx/10guti.conf

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
