name: Deploy
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRV_KEY }}
          known_hosts: "Something"
      - name: Adding known_hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Update cloud server
        run: ssh -tt ubuntu@54.209.210.217 'cd 16guti; git stash; git pull origin non-oop; yarn; /home/ubuntu/.nvm/versions/node/v12.18.4/bin/pm2 restart 10guti'
      - name: Building game
        run: ssh -tt ubuntu@54.209.210.217 'cd 16guti; yarn build'
      - name: Notify on telegram
        run: |
          curl --request POST \
            --url http://notifications.eagle3dstreaming.com:8080/message_sent \
            --header 'Content-Type: application/json' \
            --data '{
          	"input_chat_id": 1288970338,
          	"message": "New update pushed in 10guti repo:  ${{ github.event.head_commit.message }} by ${{ github.event.head_commit.author.name }}"
          }'
